# Generated by Django 3.0.8 on 2021-06-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('Creater', models.CharField(max_length=50)),
                ('Design_No', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderName', models.CharField(max_length=50)),
                ('ReciverName', models.CharField(max_length=50)),
                ('Message', models.TextField(max_length=1000)),
                ('DateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Feedbk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('Creater', models.CharField(max_length=50)),
                ('Design_No', models.IntegerField(default=0)),
                ('Comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('Sender', models.CharField(max_length=50)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('Creater', models.CharField(max_length=50)),
                ('Design_No', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('Creater', models.CharField(max_length=50)),
                ('Design_No', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_Name', models.CharField(max_length=50)),
                ('About_Design', models.CharField(max_length=300)),
                ('Select_Region', models.CharField(choices=[('Traditional', 'Traditional'), ('Casual', 'Casual'), ('Western', 'Western'), ('South', 'South'), ('Formal ', 'Formal ')], default='traditional', max_length=60)),
                ('Price', models.IntegerField(default=0)),
                ('Upload_Pictures', models.FileField(upload_to='Designs')),
                ('Make_Private', models.BooleanField(default=False)),
                ('Likes', models.IntegerField(default=0)),
            ],
        ),
    ]
